Repository micrometer-metrics/micrometer-docs, pull requests merged in 2022-08, with the labels that each got.

#244 Polish
  samples/src/test/java/io/micrometer/docs/tracing/TracingHandlerTests.java
  src/docs/implementations/wavefront.adoc
  src/docs/tracing/tracing-handler.adoc
  src/docs/tracing/tracing-testing.adoc
Labels: polish

#247 [Dynatrace] Updates and clarifications
  src/docs/implementations/dynatrace.adoc
Labels: polish

#249 Configure Dependabot to monitor Gradle plugin updates
  .github/dependabot.yml
Labels: dependencies, task

#251 Upgrade to Spring Gradle Enterprise Conventions 0.0.11
  settings.gradle
Labels: dependencies
